### ISSUE TITLE
The runtime will invoke the decorator with 2 arguments, but the decorator expects 3

### ISSUE THREAD

**Issue by tjx666** [Mervsy/TyDy#85]
I just use it as described in readme first example:

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/5ce7c903-7858-431d-bc62-da248c685f29">

**Comment by RyanMyrvold** [comment]
This pertains to the built-in decorators introduced in TypeScript 5.5. The task requires either downgrading TypeScript to a version before 5.5 or updating the decorators to align with the official TypeScript 5.5 specification.

**Comment by RyanMyrvold** [comment]
resolved by https://github.com/RyanMyrvold/Performance-Decorators/releases/tag/2.5.0
